extends CharacterBody3D

#much of the light placing dynamics was generated by chatgpt because I'm not smart enough for that
#EDIT: I did have to modify it because it was (hilariously) wrong. It got the light spawn position offset by half the length of the line
# what's the lesson? don't use AI if you can help it. its wrong often, and doesn't help you learn

@export var max_lights := 128
@export var spacing := 2
@export var light_range := 6.0
@export var light_energy := 3.0


var lights: Array[OmniLight3D] = []
var should_stop:bool = false
var brightness:float

var beam_length = 0

func _ready():
	for i in max_lights:
		var light := OmniLight3D.new()
		light.omni_range = light_range
		light.light_energy = light_energy
		light.light_color = Color.RED
		light.shadow_enabled = false
		add_child(light)
		lights.append(light)
	fire(beam_length)

func stop() -> void:
	brightness = light_energy
	should_stop = true

func _physics_process(_delta: float) -> void:
	if should_stop:
		if brightness > 0.01:
			brightness = lerp(brightness, 0.0 ,0.2)
			for light in lights:
				light.light_energy = brightness
		else:
			for light in lights:
				light.queue_free()
			lights.clear()
			should_stop = false
			queue_free()

func fire(length:float) -> void:
	$Outline.mesh.height = length
	$Outline/Beam.mesh.height = length
	#$Area3D/CollisionShape3D.shape.height = length
	$AnimationPlayer.play("InstaRayFire")
	
	var needed:int = min(int(length / spacing) + 1, max_lights)

	for i in lights.size():
		var light = lights[i]
		if i < needed:
			light.visible = true
			light.position = Vector3(0, 0, (i * spacing)-(length/2))
		else:
			light.visible = false
