extends CharacterBody3D

#much of the light placing dynamics was generated by chatgpt because I'm not smart enough for that

@export var max_lights := 128
@export var spacing := 2
@export var light_range := 6.0
@export var light_energy := 3.0


var lights: Array[OmniLight3D] = []
var should_stop:bool = false
var brightness:float

func test():
	for i in max_lights:
		var light := OmniLight3D.new()
		light.omni_range = light_range
		light.light_energy = light_energy
		light.light_color = Color.RED
		light.shadow_enabled = false
		add_child(light)
		lights.append(light)
	fire(20)

func stop() -> void:
	brightness = light_energy
	should_stop = true

func _physics_process(_delta: float) -> void:
	if should_stop:
		if brightness > 0.01:
			brightness = lerp(brightness, 0.0 ,0.2)
			print("new brightness is: " + str(brightness))
			for light in lights:
				light.light_energy = brightness
		else:
			for light in lights:
				light.queue_free()
			lights.clear()
			should_stop = false

func fire(length:float) -> void:
	$Outline.mesh.height = length
	$Outline/Beam.mesh.height = length
	#$Area3D/CollisionShape3D.shape.height = length
	$AnimationPlayer.play("IntaRayFire")
	
	var needed:int = min(int(length / spacing) + 1, max_lights)

	for i in lights.size():
		var light = lights[i]
		if i < needed:
			light.visible = true
			light.position = Vector3(0, 0, i * spacing)
		else:
			light.visible = false
